spring:
  application:
    name: HRBank
  datasource:
    url: jdbc:postgresql://localhost:5432/hr_bank
    username: team02
    password: team02314
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_schema: public